config/routes.rb
Rails.application.routes.draw do
  resources :grades
  resources :studentdata
  resources :students
  resources :classrooms
  resources :schools
  resources :schooldistricts

  devise_for :users

  namespace :admin do
    resources :users
    resources :plans

    root to: "users#index"
  end

  get 'static_pages/home'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'

  get '/students/:id/studentdatum', to: 'students#add_data_student', as: 'add_data_to_student'
  put '/students/:id/toggle', to: 'students#toggle', as: 'toggle_student'
  put '/classrooms/:id/archive', to: 'classrooms#archive', as: 'archive'
  get '/classrooms/:id/studentdatum', to: 'classrooms#add_data_classroom', as: 'add_data_to_classroom'
  post '/students/:id/studentdatum', to: 'students#studentdatum', as: 'post_data_to_student'
  post '/classroom/:id/studentdatum', to: 'classrooms#studentdatum', as: 'post_data_to_classroom'

  get '/dashboard/teachers', to: 'dashboard#teachers', as: 'teachers_dashboard'  
  post '/dashboard/grades', to: 'dashboard#set_grades', as: 'set_grades'
  
  authenticated do
    root :to => 'dashboard#index', as: :authenticated
  end

  root to: "static_pages#home"
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :school
  has_many :classrooms
  has_many :users, through: :classrooms
  has_many :students, through: :classrooms
  validates :name, :school_id, presence: true
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: [:show, :edit, :update, :destroy]
  layout "application"

  # GET /grades
  # GET /grades.json
  def index
    @grades = Grade.all
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: GradeStudentsDatatable.new(params, user: current_user, grade: params[:id], view_context: view_context) }
    end
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to @grade, notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to @grade, notice: 'Grade was successfully updated.' }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:name, :school_id)
    end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/_form.html.erb
<h3 class="card-header my-3">Filling out a new Grade for <strong><%= current_user.school.try(:name) %></strong>.</h3>

<%= form_with(model: grade, local: true) do |form| %>
 <% if grade.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

     <ul>
     <% grade.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

 <div class="form-group">
   <%= form.label :name %>
   <%= form.text_field :name, class: 'form-control' %>
 </div>

 <div class="form-group">
   <%= form.label :school_id %>
   <%= form.text_field :school, value: current_user.school.try(:name), class: 'form-control', :disabled => true  %>   
 </div>


 <div class="form-group">
   <%= form.submit 'Add New Grade', class: 'btn btn-primary my-2' %>
 </div>
<% end %>

app/views/grades/edit.html.erb
<h1 class="card-header">Editing Grade</h1>

<%= render 'form', grade: @grade %>

<%= link_to 'Show', @grade %> |
<%= link_to 'Back', grades_path %>

app/views/grades/index.html.erb
<h1 class="alert alert-primary text-center">Grades</h1>
<% if (current_user.school.grades.count > 0 if current_user.school.present?) %>
  <!-- STUDETNS BY GRADE -->
  <ul class="mt-5 nav nav-tabs" id="myTab" role="tablist">
    <% current_user.school.grades.each do |grade| %>
     <% if Student.includes(:classroom).references(:classroom).where("students.classroom_id IN (?) AND classrooms.grade_id =?", (current_user.school.classrooms.pluck(:id)), grade.id).count > 0 %>
	      <li class="nav-item col-6 col-sm-4 text-center">
	        <a class="nav-link p-3 border-bottom" id="home-tab" data-toggle="tab"
	          href="#grade<%= grade.id %>" role="tab" aria-controls="home" aria-selected="true">
	          <%= grade.name %>
	        </a>
	      </li>
	<% end %>
    <% end %>
  </ul>
  <div class="tab-content">
 	<% if current_user.school.present? %>
	    <% current_user.school.grades.each do |grade| %>
	      <% if Student.includes(:classroom).references(:classroom).where("students.classroom_id IN (?) AND classrooms.grade_id =?", (current_user.school.classrooms.pluck(:id)), grade.id).count > 0 %>
			      <div class="tab-pane fade" id="grade<%= grade.id %>" role="tabpanel" >
			        <table class="table" id="students-datatable-<%= grade.id %>" data-source="<%= grade_path(format: :json, id: grade.id) %>">
			          <thead>
			            <tr>
			              <th>Name</th>
			              <th>Classroom</th>
			              <th>Attached Data</th>
			            </tr>
			          </thead>
			          <tbody>
			          </tbody>
			        </table>
			      </div>

		      <% content_for :js do %>
		        <script type="text/javascript">
		          $(document).ready(function() {
		            $('#students-datatable-<%= grade.id %>').dataTable({
		              "processing": true,
		              "serverSide": true,
		              "ajax": $('#students-datatable-<%= grade.id %>').data('source'),
		              "columns": [
		                {"data": "full_name"},
		                {"data": "subject"},
		                {"data": "data"}
		              ]
		            });
		          });
		        </script>
		      <% end %>
		<% end %>
	    <% end %>  
    <% end %>  
  </div>
<%else%>
  <h3 class="alert alert-primary">There are no grades for this school.</h3>
 	<% if current_user.school.present? %> 	
	  <%= form_for('Grades', as: current_user.school.grades, url: set_grades_path) do |f| %>
	    <div class="form-group">
	      <%= f.submit "Create default grades!", class: "btn btn-primary" %>
	    </div>
	  <% end %>
    <% end %>  
  <h6>Or add them <%= link_to 'manually', new_grade_path %>.</h6>
<% end %>


    <%#= yield :js %>

app/views/grades/new.html.erb
<%= render 'form', grade: @grade %>

<%= link_to 'Back', :back %>

app/views/grades/show.html.erb
<p id="notice alert-success text-center"><%= notice %></p>

<div class="card-body">

<h1 class="card-header" >Grades </h1>
<p class="list-group-item">
  <strong>Name:</strong>
  <%= @grade.name %>
</p>

<p class="list-group-item">
  <strong>School:</strong>
  <%= @grade.school.name %>
</p>

<p class="mt-3 text-center">
<%= link_to 'Edit', edit_grade_path(@grade), class: 'btn btn-primary'%> 
<%= link_to 'Back', grades_path, class: 'btn btn-primary'%>
</p>
</div>