config/routes.rb
Rails.application.routes.draw do
  resources :grades
  resources :studentdata
  resources :students
  resources :classrooms
  resources :schools
  resources :schooldistricts

  devise_for :users

  namespace :admin do
    resources :users
    resources :plans

    root to: "users#index"
  end

  get 'static_pages/home'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'

  get '/students/:id/studentdatum', to: 'students#add_data_student', as: 'add_data_to_student'
  put '/students/:id/toggle', to: 'students#toggle', as: 'toggle_student'
  put '/classrooms/:id/archive', to: 'classrooms#archive', as: 'archive'
  get '/classrooms/:id/studentdatum', to: 'classrooms#add_data_classroom', as: 'add_data_to_classroom'
  post '/students/:id/studentdatum', to: 'students#studentdatum', as: 'post_data_to_student'
  post '/classroom/:id/studentdatum', to: 'classrooms#studentdatum', as: 'post_data_to_classroom'

  get '/dashboard/teachers', to: 'dashboard#teachers', as: 'teachers_dashboard'  
  post '/dashboard/grades', to: 'dashboard#set_grades', as: 'set_grades'
  
  authenticated do
    root :to => 'dashboard#index', as: :authenticated
  end

  root to: "static_pages#home"
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  enum term: [:spring, :summer, :fall, :winter]
  belongs_to :school
  belongs_to :grade
  belongs_to :user
  has_many :students
  has_many :studentdatum, :through => :students
  validates :subject, :grade_id, :term, :school_id, :user_id, presence: true
  before_save :default_values

  def default_values
    self.archived ||= false # note self.status = 'P' if self.status.nil? might be safer (per @frontendbeauty)
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy, :add_data_classroom, :archive]
  before_action :authenticate_user!
  layout "application"

  # GET /classrooms
  def index
    @classrooms = Classroom.where(user_id: current_user.id)
    respond_to do |format|
      format.html
      format.json { render json: ClassroomDatatable.new(params, user: current_user, view_context: view_context) }
    end
  end

  # GET /classrooms/1
  def show
    respond_to do |format|
      format.html
      format.json { render json: ClassroomStudentsDatatable.new(params, classroom: params[:id], view_context: view_context) }
    end
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
    @students = Student.all
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms
  def create
    @classroom = Classroom.new(classroom_params)
    if current_user.role == "teacher"
      @classroom.user_id = current_user.id
    end
    @classroom.school_id = current_user.school_id

    puts @classroom
    if @classroom.save
      redirect_to (classrooms_path), notice: 'Classroom was successfully created.'
    else
      render :new
    end

  end

  # PATCH/PUT /classrooms/1
  def update
    if @classroom.update(classroom_params)
      redirect_to @classroom, notice: 'Classroom was successfully updated.'
    else
      render :edit
    end
  end

  def archive
    @classroom.archived = true

    if @classroom.save
        redirect_to classrooms_path, notice: 'Data was successfully added.'
      else
        redirect_to classroom_path(params[:id]), notice: 'Data was not added.'
    end
  end

  # GET /classrooms/1/studentdatum
  def add_data_classroom
    @studentdatum = Studentdatum.new
  end

  # POST /classrooms/1/studentdatum
  def studentdatum
    @student_data = Studentdatum.new(studentdata_params)
    @student_data.student_id = params[:id]

    if @student_data.save
      redirect_to student_path(params[:id]), notice: 'Data was successfully added.'
      else
        render :new
    end
  end

  # DELETE /classrooms/1
  def destroy
    @classroom.destroy
    redirect_to classrooms_url, notice: 'Classroom was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classroom_params
      params.require(:classroom).permit(:subject, :user_id, :grade_id, :term)
    end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/_form.html.erb
<div class="form-group">
<% if @classroom.id %>
  <h3 class="card-header my-1">Editing <strong><%= "#{@classroom.subject} (#{@classroom.term.upcase})" %>'s</strong> data</h3>
  <h3 class="card-header my-1">At <strong><%= current_user.school.name %>'s</strong>, <strong> <%= @classroom.students.count %></strong> student(s) signed up.</h3>
<% end %>
</div>

<%= form_with(model: classroom, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :subject%>
    <%= form.text_field :subject, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :grade %>
    <%= form.collection_select(:grade_id, Grade.where(school_id: current_user.school_id), :id, :name,
      {:prompt => 'Select school grade'}, class: 'form-control', :selected => @classroom.grade_id)%>
      <% if current_user.role == 'teacher' %>
        <%= 'Grade not shown? Contact your school admin.' %>
      <% elsif current_user.role == 'admin' %>
        <%= 'Grade not shown? ' %><%= link_to('Add it!', new_grade_path) %>
      <%end%>
  </div>

  <div class="form-group">
    <%= form.label :term %>
    <%= form.select :term, options_for_select(Classroom.terms.keys, class: 'form-control'),
    {},{class:"form-control m-b", style:"text-transform: capitalize"} %>
  </div>

  <% if current_user.role == "admin"%>
    <div class="form-group">
      <%= form.label "Teacher" %>
      <%= form.collection_select(:user_id, User.where(school_id: current_user.school_id).reject { |usr| usr.role == "admin"}, :id, :full_name, {:prompt => 'Select Teacher'},
        class: 'form-control', :selected => @classroom.user_id)%>
    </div>
  <% else %>
  <div class="form-group">
    <%= form.label "Teacher" %>
    <%= form.text_field :user, value: current_user.full_name, class: 'form-control',   :disabled =>true%>
  </div>
  <% end%>

  <div class="form-group">
    <%= form.submit 'Update Classroom', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/classrooms/add_data_classroom.html.erb
<div class="row mb-5 align-items-center justify-content-center">
  <div class="col-lg-12 text-center ">
      <% if current_user.role == 'teacher' %>
        <h3>Adding data to classroom <strong><%= @classroom.subject %></strong></h3>
        <h4>There's currently <strong><%= @classroom.students.count %> student(s)</strong> registered for this classroom.</h4>
      <% elsif current_user.role == 'admin' %>
        <h2><%= @classroom.subject %> <strong>(<%= @classroom.term.upcase %>)</strong> <%= @classroom.grade.name %></h2>
        <h4>By teacher, <strong><%= @classroom.user.full_name %></strong>.</h4>           
        <h4>There's currently <strong><%= @classroom.students.count %> student(s)</strong> registered for this classroom.</h4>
      <% end %>

      <%= form_with(model: @studentdatum, local: true) do |form| %>
        <div class="row">
          <div class="form-group col-lg-12">
            <%= form.label :title%>
            <%= form.text_field :title, class: 'form-control' %>
          </div>
          <div class="form-group col-lg-12">
            <%= form.label :text %>
            <%= form.text_area :text, class: 'form-control' %>
          </div>
          <div class="list-group-item d-flex flex-column  buttons mx-auto" style="text-align:center;">
            <%#%= link_to 'Documents', classrooms_path, class: 'btn btn-success my-1' %>
            <%#%= link_to 'Upload', classrooms_path, class: 'btn btn-success my-1' %>
            <%= link_to 'Save Data', "#", class: 'btn btn-success my-1' %>
            <small>Download report</small>
          </div>
        </div>
      <% end %>
  </div>
  <div class="row" style="padding-top:20px;">
    <% @classroom.students.each do |student| %>
      <div class="card">
        <div class="card-header" style="text-align:center;">
          <p class="card-title"><strong><%= student.full_name %></strong></p>              
        </div>
        <div class="card-content" style="margin-left:auto; margin-right:auto;
        padding-top:10px; padding-bottom:10px;">
          <input type="checkbox"/>
          <span>Attach data?</span>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/classrooms/edit.html.erb
<%= render 'form', classroom: @classroom %>

<%= link_to 'Back', :back %> |
<%= link_to 'Archive', archive_path, method: :put, data: { confirm: 'Do you really want to archive class?' } %>

app/views/classrooms/index.html.erb
<div class="row mb-5 d-flex justify-content-center align-items-center ">

    <div class="list-group-item d-flex flex-column text-center buttons rounded-0  my-2" >
      <%= link_to 'Add Class', new_classroom_path, class: 'btn btn-success my-1 ' %> 
      <small >Fill out a new class.</small>      
    </div> 

    <div class="col-lg-7 col-md-6 text-center my-2">
    <% if current_user.role == 'teacher' %>
     <h2>Teacher's <strong><%= current_user.full_name %></strong> Classrooms</h2>
     <h3>You're marked as teacher accross <strong><%= current_user.school.grades.count%> different</strong> grades.</h3>
    <% elsif current_user.role == 'admin' %>
     <h2><strong><%= current_user.school.name %>'s</strong> classrooms!</h2>
     <h4>There's <strong><%= current_user.school.classrooms.count %> different</strong>  classrooms registered across 
     <strong><%= current_user.school.grades.count if current_user.school.present? %> different</strong> grades.</h4>
     <h4>Currently, <strong><%= current_user.school.users.where(role: 'teacher').count if current_user.school.present? %> user(s)</strong> marked as <strong>Teacher</strong>.</h4>
    <% end %>
    </div>

    <div class="list-group-item d-flex flex-column  buttons text-center rounded-0 my-2" >
      <%= link_to 'Documents', "#", class: 'btn btn-info my-1' %>
      <small>All classes files</small>      
      
    </div>
    
</div>

<% if current_user.school.present? %>   
<% if current_user.school.classrooms.count > 0 %>
  <table class="table table-responsive-md" id="classrooms-datatable" data-source="<%= school_path(format: :json, id: current_user.school_id) %>">
    <thead>
      <tr>
        <th>Subject</th>
        <th>Grade</th>
        <th>Teacher</th>
        <th>Students</th>
        <th>Status</th>
      </tr>
    </thead>

    <tbody>
    </tbody>
  </table>
<% else %>
  <h3 class="alert alert-primary">No classrooms registered for this school.</h3>
<% end %>
<% end %>

<% content_for :js do %>
  <script type="text/javascript">
    $(document).ready(function() {
      $.fn.dataTable.ext.errMode = 'none';
      $('#classrooms-datatable').dataTable({
        "processing": true,
        "serverSide": true,
        "ajax": $('#classrooms-datatable').data('source'),
        "columns": [
          {"data": "subject"},
          {"data": "grade"},
          {"data": "teacher"},
          {"data": "students"},
          {"data": "archived"}
         // {"data": "subject"},
        //  {"data": "student"}, 
        ///  {"data": "actions"},
        //  {"data": "show"},
        //  {"data": "delete"}
        ]
      });
    });
  </script>
<% end %>

app/views/classrooms/new.html.erb
<h3 class="card-header my-1">Fill out a new class!</h3>
<h3 class="card-header my-1">Class being filled for school <strong><%= current_user.school.name %></strong>.</h3>

<%= render 'form', classroom: @classroom %>

<%= link_to 'Back', classrooms_path %>

app/views/classrooms/show.html.erb
<div class="row mb-5 align-items-center justify-content-center align-items-center">

    <div class="list-group-item d-flex flex-column text-center buttons rounded-0  my-2" >
        <%= link_to 'Edit Class', edit_classroom_path(@classroom.id), class: 'btn btn-warning my-1' %> 
        <small >Edit class data</small>      
        <% if !@classroom.archived %>
          <%= link_to 'Archive Class', archive_path, class: 'btn btn-danger my-1', method: :put, data: { confirm: 'Do you really want to archive class?' } %>
          <small ><span style="color:red;">(irreversible)</span></small>
        <% end %>
      </div>


      <div class="col-lg-7 col-md-6 text-center my-2 text-center ">
          <% if current_user.role == 'teacher' %>
            <h2><strong><%= @classroom.subject %></strong></h2>
            <% if @classroom.archived %>
              <h5 style="color:gray"><strong>(Class archived)</strong></h5>
            <%else%>
              <h3>You're marked as teacher accross <strong><%= current_user.school.grades.count%> different</strong> grades.</h3>              
            <% end %>
          <% elsif current_user.role == 'admin' %>
           <h2><%= @classroom.subject %> <strong>(<%= @classroom.term.upcase %>)</strong> <%= @classroom.grade.name %></h2>
           <h4>By teacher, <strong><%= @classroom.user.full_name %></strong>.</h4>
            <% if @classroom.archived %>
                <h5 style="color:gray"><strong>(Class archived)</strong></h5>
              <%else%>
                <h4>There's currently <strong><%= @classroom.students.count %> student(s)</strong> registered for this classroom.</h4>
            <% end %>
          <% end %>
      </div>

      <div class="list-group-item d-flex flex-column text-center buttons rounded-0  my-2" >
          <%= link_to 'Documents', "#", class: 'btn btn-info my-1' %> 
          <small >Class files</small>      
          <%= link_to 'Add data', add_data_to_classroom_path(@classroom.id), class: 'btn btn-success my-1' %>
          <small >Select students</small>
          <%= link_to 'Upload', "#", class: 'btn btn-primary my-1' %>
          <small >Class content file</small>     
        </div>
</div>    

<table class="table table-responsive-md" id="classroom-students-datatable" data-source="<%= classroom_path(format: :json) %>">
    <thead>
      <tr>
        <th>Name</th>
        <th>Status</th>
        <th>Attached Data (by me)</th>
        <th>Actions</th>
      </tr>
    </thead>
  
    <tbody>
    </tbody>
  </table>

<% content_for :js do %>
<script type="text/javascript">
  $(document).ready(function() {
    $('#classroom-students-datatable').dataTable({
      "processing": true,
      "serverSide": true,
      "ajax": $('#classroom-students-datatable').data('source'),
      "columns": [
        {"data": "full_name"},
      //  {"data": "grade"},
        {"data": "status"},
        {"data": "studentdata"},
        {"data": "actions"}
      //  {"data": "is_active"},
      //  {"data": "edit"}
      ]
    });
  });
</script>
<% end %>