config/routes.rb
Rails.application.routes.draw do
  resources :grades
  resources :studentdata
  resources :students
  resources :classrooms
  resources :schools
  resources :schooldistricts

  devise_for :users

  namespace :admin do
    resources :users
    resources :plans

    root to: "users#index"
  end

  get 'static_pages/home'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'

  get '/students/:id/studentdatum', to: 'students#add_data_student', as: 'add_data_to_student'
  put '/students/:id/toggle', to: 'students#toggle', as: 'toggle_student'
  put '/classrooms/:id/archive', to: 'classrooms#archive', as: 'archive'
  get '/classrooms/:id/studentdatum', to: 'classrooms#add_data_classroom', as: 'add_data_to_classroom'
  post '/students/:id/studentdatum', to: 'students#studentdatum', as: 'post_data_to_student'
  post '/classroom/:id/studentdatum', to: 'classrooms#studentdatum', as: 'post_data_to_classroom'

  get '/dashboard/teachers', to: 'dashboard#teachers', as: 'teachers_dashboard'  
  post '/dashboard/grades', to: 'dashboard#set_grades', as: 'set_grades'
  
  authenticated do
    root :to => 'dashboard#index', as: :authenticated
  end

  root to: "static_pages#home"
end

app/models/student.rb
class Student < ApplicationRecord

  include PgSearch
  pg_search_scope :search,
                 :against => :name,
                  :using => {
                    :trigram => {
                      :threshold => 0.1
                    }
                  }

  belongs_to :classroom
  has_one :grade, through: :classroom
  has_one :grade_id, through: :grade
  has_one :school, through: :classroom
  has_many :studentdatum
  validates :first_name, :last_name, :middlename, :isactive, :classroom_id, presence: true

  before_save :save_student_name


  def full_name
    "#{first_name} #{middlename} #{last_name}"
  end

  def status
    isactive ? "Active" : "Inactive"
  end

  private
     
     ##this is used for PG Search
     def save_student_name
          self.name = full_name
     end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student,  only: [:show, :edit, :update, :toggle, :destroy, :add_data_student, :studentdatum]
  before_action :authenticate_user!
  before_action :set_studentdatum, only: [:add_data_student]
  layout "application"

  # GET /students
  def index
    @students = Student.where(school: current_user.school_id)
    respond_to do |format|
      format.html
      format.json { render json: StudentDatatable.new(params, school: current_user.school_id, view_context: view_context, query: params[:query]) }
    end
  end

  # GET /students/1
  def show
    respond_to do |format|
      format.html
      format.json { render json: StudentdataDatatable.new(params, student: params[:id], view_context: view_context) }
    end
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to (students_path), notice: 'Student was successfully created.'
    else
      render :new
    end
  end



  def toggle
    @student.isactive = !@student.isactive
    if @student.save
      redirect_back(fallback_location: :root, notice: 'Status updated!')
    else
      redirect_back(fallback_location: :root, alert: 'Could not update status!')
    end
  end

  def drop
    @student.classroom_id = null
    if @student.save
      redirect_back(fallback_location: :root, notice: 'Student updated!')
    else
      redirect_back(fallback_location: :root, alert: 'Could not drop student!')
    end
  end

  # PATCH/PUT /students/1
  def update
    if @student.update(student_params)
      redirect_to @student, notice: 'Student was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /students/1
  def destroy
    @student.destroy

    redirect_to students_url, notice: 'Student was successfully destroyed.'
  end


    # GET /students/1/studentdatum
    def add_data_student
    end
  
    # POST /students/1/studentdatum
    def studentdatum
      @studentdatum = Studentdatum.new(studentdata_params)
      @studentdatum.user_id = current_user.id
      if @studentdatum.save
        redirect_to student_path(params[:id]), notice: 'Data was successfully added.'
      else
        render :add_data_student
      end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    def set_studentdatum
      @studentdatum = Studentdatum.new(student_id: params[:id], classroom_id: @student.classroom.id, user_id: current_user.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :middlename, :isactive, :classroom_id)
    end

    def studentdata_params
      params.require(:studentdatum).permit(:title, :text, :student_id, :classroom_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :middle_name %>
    <%= form.text_field :middlename, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: 'form-control' %>
  </div>

  <div class="field">
      <%= form.label "Is active?" %>
      <%= form.check_box :isactive %>
  </div>

  <div class="form-group">
    <%= form.label :classroom %>
    <% if current_user.role == 'admin' %>
      <%= form.collection_select(:classroom_id, Classroom.where(school_id: current_user.school_id), :id, :subject, {:prompt => 'Select Classroom'}, class: 'form-control', :selected => @student.classroom_id)%>
    <% elsif current_user.role == 'teacher' %>
      <%= form.collection_select(:classroom_id, Classroom.where(user_id: current_user.id), :id, :subject, {:prompt => 'Select Classroom'}, class: 'form-control', :selected => @student.classroom_id)%>
    <% end %>
    <%= form.label 'Dont see your classroom?' %>
    <%= link_to 'Add it!', new_classroom_path %>
  </div>

  <div class="form-group">
    <%= form.submit 'Save Student', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/students/add_data_student.html.erb
<h3>Attach data to <strong><%= @student.full_name %></strong></h3>

    <%= form_with(model: @studentdatum, url: post_data_to_student_path, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :text %>
        <%= form.text_area :text, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :student %>
        <%= form.collection_select(:student_id, Student.all, :id, :full_name, {:prompt => 'Select Student'},
        class: 'form-control', :selected => :student_id )%>
      </div>
      <div class="form-group">
        <%= form.label :classroom %>
        <%= form.collection_select(:classroom_id, Classroom.where(id: @student.classroom_id), :id,
        :subject, {:prompt => 'Select Classroom'}, class: 'form-control',
        :selected => :classroom_id )%>
      </div>


    <div class="form-group">
      <%= form.submit 'Attach data', class: 'btn btn-primary' %>
    </div>
  <% end %>
  <%= link_to 'Back', :back %>

  <% content_for :js do %>
    <script type="text/javascript">
    $(document).ready(function () {
        document.getElementById('studentdatum_student_id').setAttribute("readonly", "")
        document.getElementById('studentdatum_classroom_id').setAttribute("readonly", "")
    })
    </script>
  <% end %>

app/views/students/edit.html.erb
<%= render 'form', student: @student %>

<%= link_to 'Back', :back %>

app/views/students/index.html.erb
<div class="row mb-5 align-items-center justify-content-center align-items-center">

  <div class="list-group-item d-flex flex-column  buttons rounded-0 text-center my-2">
    <%= link_to 'Add Student', new_student_path, class: 'btn btn-success my-1' %> 
    <small >Register a new student.</small>      
  </div>

  <div class="col-lg-7 col-md-5 text-center rounded-0 my-2">
    <h2><strong><%= current_user.school.name if current_user.school.present? %></strong> students!</h2>      
    <h3>There's currently <strong><%= @students.count %> student(s)</strong> registered.</h3>
  </div>

  <div class="list-group-item d-flex flex-column  buttons rounded-0 text-center my-2">
    <%#%= link_to 'Documents', classrooms_path, class: 'btn btn-success my-1' %>
    <%#%= link_to 'Upload', classrooms_path, class: 'btn btn-success my-1' %>
    <%= link_to 'Students Report', "#", class: 'btn btn-info my-1' %>
      <small>Download report</small>
    <%= link_to 'Upload', "#", class: 'btn btn-primary my-1' %>
    <small >Global's students file</small>
  </div>

</div>
<% if current_user.school.present? %>
<% if (current_user.school.students.count > 0)%>
<table class="table table-responsive-md" id="students-datatable" data-source="<%= students_path(query: params[:query], format: :json) %>">
  <thead>
    <tr>
      <th>Name</th>
      <th>Classroom</th>
      <th>Grade</th>
      <th>Status</th>
      <th>Attached Data</th>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>
<% else %>
<h3 class="alert alert-danger">No students registered for this school.</h3>
<% end %>
<% end %>


<% content_for :js do %>
  <script type="text/javascript">
    $(document).ready(function() {
      $.fn.dataTable.ext.errMode = 'none';
      $('#students-datatable').dataTable({
        "processing": true,
        "serverSide": true,
        "ajax": $('#students-datatable').data('source'),
        "columns": [
          {"data": "full_name"},
        //  {"data": "grade"},
          {"data": "classroom"},
          {"data": "grade"},
          {"data": "status"},
          {"data": "studentdata"}
        //  {"data": "is_active"},
        //  {"data": "edit"}
        ]
      });
    });
  </script>
<% end %>

 <%= yield :js %>

app/views/students/new.html.erb
<h3 class="card-header my-5">Filling out a new student for <strong><%= current_user.school.name %></strong>.</h3>

<%= render 'form', student: @student %>

<%= link_to 'Back', :back %>

app/views/students/show.html.erb
<div class="row mb-5 align-items-center">
    <div class="list-group-item d-flex flex-column  buttons" style="text-align:center;">
        <%= link_to 'Sign up', '#', class: 'btn btn-success my-1' %> 
        <small >Add to classroom</small>
        <%= link_to 'Add data', add_data_to_student_path(@student.id), class: 'btn btn-info my-1' %> 
        <small >Attach student data</small>     
      </div> 
      <div class="col-lg-8 text-center ">
           <h2>Student <strong><%= @student.full_name %>'s</strong></h2>
           <h4>Signed up currently for <strong><%= @student.classroom.subject %> (<%= @student.classroom.term.upcase %>)</strong>.<br>
            By <strong> <%= @student.classroom.user.full_name %></strong></h4>
           <h4><strong><%= @student.studentdatum.count %> different</strong> data titles found.</h4>
          </div>
          <div class="list-group-item d-flex flex-column  buttons" style="text-align:center;">
              <%= link_to 'Edit', edit_student_path(@student.id), class: 'btn btn-warning my-1' %>
              <small>Edit student data</small>
              <%= link_to 'Upload', '#', class: 'btn btn-primary my-1' %>
              <small>Class content file</small>
          </div>
</div>

<% if @student.studentdatum.count > 0 %>
  <table class="table" id="studentdata-datatable" data-source="<%= student_path(format: :json) %>">
    <thead>
      <tr>
        <th>Title</th>
        <th>Text</th>
        <th>Given At</th>
        <th>Creation Date</th>

      </tr>
    </thead>

    <tbody>
    </tbody>
  </table>
<% end %>


<% content_for :js do %>
  <script type="text/javascript">
    $(document).ready(function() {
      $('#studentdata-datatable').dataTable({
        "processing": true,
        "serverSide": true,
        "ajax": $('#studentdata-datatable').data('source'),
        "columns": [
          {"data": "title"},
          {"data": "text"},
          {"data": "classroom"},
          {"data": "created_at"}
          /*{"data": "title"},
          {"data": "text"},
          {"data": "classroom"},
          {"data": "teacher"},
          {"data": "date"}*/
        ]
      });
    });
  </script>
<% end %>