config/routes.rb
Rails.application.routes.draw do
  resources :grades
  resources :studentdata
  resources :students
  resources :classrooms
  resources :schools
  resources :schooldistricts

  devise_for :users

  namespace :admin do
    resources :users
    resources :plans

    root to: "users#index"
  end

  get 'static_pages/home'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'

  get '/students/:id/studentdatum', to: 'students#add_data_student', as: 'add_data_to_student'
  put '/students/:id/toggle', to: 'students#toggle', as: 'toggle_student'
  put '/classrooms/:id/archive', to: 'classrooms#archive', as: 'archive'
  get '/classrooms/:id/studentdatum', to: 'classrooms#add_data_classroom', as: 'add_data_to_classroom'
  post '/students/:id/studentdatum', to: 'students#studentdatum', as: 'post_data_to_student'
  post '/classroom/:id/studentdatum', to: 'classrooms#studentdatum', as: 'post_data_to_classroom'

  get '/dashboard/teachers', to: 'dashboard#teachers', as: 'teachers_dashboard'  
  post '/dashboard/grades', to: 'dashboard#set_grades', as: 'set_grades'
  
  authenticated do
    root :to => 'dashboard#index', as: :authenticated
  end

  root to: "static_pages#home"
end

app/views/layouts/_errors.html.erb
  <% flash.each do |name, msg| %>
     <% if user_signed_in? %>
      <div class="alert alert-success text-center alert-dismissible fade show" role="alert">
   <%= content_tag(:div, msg) %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
   
     <% else %>
      <div class="alert alert-danger z-index-2 text-center alert-dismissible fade-out show" role="alert">
   <%= content_tag(:div, msg) %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
   
      <% end %>
  <% end %>
     

    
       
  
  
  

app/views/layouts/_footer.html.erb
  <% if user_signed_in? %>
  <div class="footer">
<footer class="pt-5 mt-auto  bg-dark ">
  <div class="row ">
    
    <div class="col-12 col-md-4">
      <ul class="list-unstyled center-text ">
        <li class=" text-white h5 pl-0 pl-md-3">Features</li>
        <li><a class="text-muted pl-0 pl-md-3" href="#">Stuff to developers</a></li>
        <li><a class="text-muted pl-0 pl-md-3" href="#">Store Assessment </a></li>
        <li><a class="text-muted pl-0 pl-md-3" href="#">Team feature</a></li>
        <li><a class="text-muted pl-0 pl-md-3" href="#">Another one</a></li>
        <li><a class="text-muted pl-0 pl-md-3" href="#">Last time</a></li>
      </ul>
    </div>
    <div class="col-12 col-md-4 border-right border-left">
      <ul class="list-unstyled text-small center-text">
        <li class="text-white h5">Resources</li>
        <li><a class="text-muted" href="#">Another resource</a></li>
        <li><a class="text-muted" href="#">Final resource</a></li>
        <li><a class="text-muted" href="#">Resource</a></li>
        <li><a class="text-muted" href="#">Contact</a></li>
      </ul>
    </div>
    <div class="col-12 col-md-4 pl-0">
      <ul class="list-unstyled text-small center-text">
        <li class="text-white h5 pl-2 pl-md-3">About</li>
        <li><a class="text-muted pl-2 pl-md-3" href="#">Locations</a></li>
        <li><a class="text-muted pl-2 pl-md-3" href="#">Privacy</a></li>
        <li><a class="text-muted pl-2 pl-md-3" href="#">Terms</a></li>
        <li><a class="text-muted pl-2 pl-md-3" href="#">Team</a></li>
      </ul>
    </div>
    <div class="col-12 text-center border-top-gray mt-4 mt-md-5">
      <small class="d-block text-white py-3 ">&copy; 2017-2018</small>
    </div>
  </div>
</footer>
<div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5 ">
    <div class="" >
      <% if user_signed_in? %>
         <h1 class="h4 mt-2" >
          <%= link_to "Teacher Data", root_path, id: "logo", class: "  " %>
         </h1>
      <% else %>
        <h1 class="h4 mt-2">
         <%= link_to "Teacher Data", static_pages_home_path, id: "logo", class: "" %>
         </h1>
      <% end %> 
    </div>
      
      <button class="navbar-toggler rounded-0 border-primary" type="button" data-toggle="collapse"  data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    
    <% if user_signed_in? %> 
     
    <nav class="d-flex flex-column flex-lg-row ml-auto  text-center" >

      <% if current_user.role == 'superadmin' %> 
       <ul class="navbar-nav ">
        <li class="nav-item dropdown ">
        <a class="nav-link hover-a text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Menu
        </a>
        <div class="dropdown-menu bg-dark" style="margin-top:9.5px;"aria-labelledby="navbarDropdown">
         <%= link_to('Dashboard', dashboard_path, class: "p-2 hover-a") %> 
         <%= link_to('Students', students_path, class: "p-2 hover-a d-block") %> 
        <%= link_to('School Districts', schooldistricts_path, class: "p-2 hover-a d-block") %>    
        </li>
        </ul>
        <%= link_to('Admin', "/admin", class: "p-2 hover-a") %>
      <% elsif current_user.role == 'admin' %>

        <%= link_to('Dashboard', dashboard_path, class: "p-2 hover-a") %>
        <%= link_to('Grades', grades_path, class: "p-2 hover-a") %>        
        <%= link_to('Classrooms', classrooms_path, class: "p-2 hover-a") %>
        <%= link_to('Students', students_path, class: "p-2 hover-a") %>

      <% elsif current_user.role == 'teacher' %>
        <%= link_to('Dashboard', dashboard_path, class: "p-2 hover-a") %>
        <%= link_to('Classrooms', classrooms_path, class: "p-2 hover-a") %>
        <%= link_to('Students', students_path, class: "p-2 hover-a") %>
      <% end %>
    </nav>
    
  <div class="mx-2 d-flex justify-content-center ">
      <%= form_tag students_path, method: :get, class: "form-inline  my-2 my-lg-0"  do %>
        <%= text_field_tag "query", params[:query], placeholder: "Search Student", class: "form-control col-7 text-left ml-3 rounded-0" %>
        <button class="btn btn-outline-success col-4 rounded-0" type="submit">Search</button>
      <% end %>
    </div>
 


    <div class="d-flex flex-row  align-items-center justify-content-center">
       <%= link_to edit_user_registration_path, class: "size-icon fas fa-edit mb-1 d-flex flex-row " do %>
          <%= content_tag :span, "Edit", :class => "fz-icons ml-1 mt-1" %>
        <% end %>
        <%= link_to destroy_user_session_path, method: :delete, class: "size-icon fas fa-sign-out-alt d-flex flex-row " do %>
          <%= content_tag :span, "Logout", :class => "fz-icons ml-2" %>
        <% end %>
    </div>

  <% else %>

    <div class="col-12 d-flex flex-row ml-auto align-items-center justify-content-center justify-content-lg-end">
         <%= render partial: "layouts/navbar_links" %>
    </div>
  <% end %>
  
  </div>
 </nav>
 

             

app/views/layouts/_navbar_links.html.erb
<%= link_to new_user_registration_path, class: "fas fa-user-plus signup-icon d-flex flex-row" do %>
     <%= content_tag :span, "Signup", :class => "fz-icons ml-2" %>
<% end %>

<%= link_to new_user_session_path, class: "fas fa-sign-in-alt size-icon d-flex flex-row" do %>
     <%= content_tag :span, "Login", :class => "fz-icons ml-2 mt-1" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Teacher Data</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'  %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/errors' %>

      <%= yield %>
      
      <pre>
        <%= debug(params) if Rails.env.development? %>
      </pre>
    </div>
      
    <%= yield :js %>
        <script>
    $(document).ready(function () {
    $(".alert-danger").fadeTo(2000, 1500).slideUp(1500, function(){
    $(".alert-danger").slideUp(500);
});
    $(".alert-success").fadeTo(2000, 1500).slideUp(1500, function(){
    $(".alert-success").slideUp(1500);
});
    })

    </script>
    
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <title><%= yield(:title) %> || Dashboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/errors' %>

      <%= yield %>
      <pre>
        <%= debug(params) if Rails.env.development? %>
      </pre>
    </div>

    <%= yield :js %>
    <script>
    $(document).ready(function () {
    $(".alert-danger").fadeTo(2000, 1500).slideUp(1500, function(){
    $(".alert-danger").slideUp(1500);
});
    $(".alert-success").fadeTo(2000, 1500).slideUp(1500, function(){
    $(".alert-success").slideUp(1500);
});
    })

    </script>
<%= render 'layouts/footer' %>
  </body>
</html>